[dev]
  command = "npm run start"
  targetPort = 4200

[build]
  publish = "_public/"
  command = "npm run publish:prod"

[context.branch-deploy]
  command = "npm run publish:stage"

[context.deploy-preview]
  command = "npm run publish:stage"

[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=365000000, immutable"

# Redirect any URLs with the language code in them already
[[redirects]]
  from = "/en-US/*"
  to = "/:splat"
  status = 301
  force = true

# Important: Per shadowing rules, URLs for the
# _non-default_ language-specific content files
# are served without redirects.

# Redirect for end-userâ€™s browser preference override
[[redirects]]
  from = "/*"
  to = "/es-ES/:splat"
  status = 302
  conditions = {Language = ["es-ES"]}

# Default
[[redirects]]
  from = "/*"
  to = "/en-US/:splat"
  status = 200
